// Placeholder for deploy.yml
name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_PASS }}

    - name: Build Backend Docker Image
      run: |
        docker build -t hamzus17/backend:latest ./backend
        docker push hamzus17/backend:latest

    - name: Build Frontend Docker Image
      run: |
        docker build -t hamzus17/frontend:latest ./frontend
        docker push hamzus17/frontend:latest

    - name: Set up Kubeconfig
      run: |
        mkdir ~/.kube
        echo "${{ secrets.KUBECONFIG_FILE }}" > ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./k8s
